
version: '3'
services:
  service1:
    build:
      context: ./DockerfileForRuby3-0-2
      dockerfile: Dockerfile
  service2:
    build:
      context: ./DockerfileForRuby2-7-4
      dockerfile: Dockerfile
